name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - ruby-version: '3.1'
            rails-version: '7.0'
          - ruby-version: '3.2'
            rails-version: '7.1'
          - ruby-version: '3.3'
            rails-version: '7.2'
          - ruby-version: '3.4'
            rails-version: '8.0'
          - ruby-version: '3.4'
            rails-version: '8.1'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
      - name: Run Tests
        run: bundle exec rspec
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
