name: Unit Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [2.7, 3.0]
        rails-version: ['5.0', '5.1', '5.2', '6.0', '6.1']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
      - name: Run Tests
        run: bundle exec rspec
        env:
          BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails-version }}.gemfile
